# Generated by Django 5.1.2 on 2024-10-18 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_area_price'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='owner',
        ),
        migrations.AddField(
            model_name='area',
            name='provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
    ]
