# Generated by Django 5.1.2 on 2024-10-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('language', models.CharField(choices=[('EN', 'English'), ('SP', 'Spanish')], default='EN', max_length=2)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=4)),
            ],
        ),
    ]
