# Generated by Django 5.1.2 on 2024-10-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_currency_customuser_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
